run:
  timeout: 5m
  tests: true

linters:
  enable:
    - goimports
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - typecheck
    - misspell
    - gosec

linters-settings:
  gosec:
    excludes:
      - G101  # hardcoded credentials (false positives in tests)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
