package terraform

import (
	"crypto/sha256"
	"encoding/hex"

	"github.com/tiziano093/infra-composer-cli/internal/catalog"
)

// WiredInput describes one input variable of a ResolvedModule whose
// value flows from another module instance in the same plan. The
// generator emits `module.<FromInstance>.<FromOutput>` in the module
// block.
type WiredInput struct {
	VarName      string
	FromModule   string // catalog module name, kept for diagnostics
	FromInstance string
	FromOutput   string
}

// ExternalInput is one input variable that must be supplied by the
// stack consumer. The generator emits a corresponding `variable` block
// in variables.tf and references `var.<VarName>` in the module call.
type ExternalInput struct {
	// VarName is the rendered top-level variable identifier
	// (`<module>_<input>`) used in both variables.tf and the module
	// block. Module-name prefixing avoids collisions when two modules
	// share an input name (e.g. cidr_block).
	VarName string
	// LocalName is the original input name within the catalog module;
	// used when wiring the value back into the module block.
	LocalName   string
	Type        string
	Description string
	Required    bool
	Sensitive   bool
	Default     any
}

// StackOutput is one output exported by the composed stack at the top
// level. ExportedName follows the `<module>_<output>` convention to
// avoid collisions across modules.
type StackOutput struct {
	ExportedName string
	Module       string
	Instance     string
	Output       string
	Description  string
	Sensitive    bool
}

// ResolvedModule is a single module instance in the plan, after source
// resolution and wiring decisions.
type ResolvedModule struct {
	Module          *catalog.ModuleEntry
	Instance        string
	Source          SourceSpec
	WiredInputs     []WiredInput
	ExternalInputs  []ExternalInput
	StackOutputs    []StackOutput
	UnwiredWarnings []string // per-variable diagnostics for refs that fell through
}

// ComposePlan is the deterministic blueprint generated by Plan() and
// consumed by Generate(). It is fully self-describing — the generator
// never reaches back into the catalog.
type ComposePlan struct {
	Provider        string // canonical "<namespace>/<name>"
	ProviderName    string // last segment, used as the local provider key
	ProviderVersion string
	Modules         []ResolvedModule // topologically ordered, deps first
	Warnings        []string         // plan-level diagnostics
}

// GeneratedFile is one rendered artefact returned by Generate. Path is
// relative to the compose output directory.
type GeneratedFile struct {
	Path    string
	Content []byte
}

// SHA256Hex returns the hex-encoded SHA-256 of the file content. Used by
// dry-run output so consumers can diff plans without dumping bodies.
func (f GeneratedFile) SHA256Hex() string {
	sum := sha256.Sum256(f.Content)
	return hex.EncodeToString(sum[:])
}
