# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfraComposer < Formula
  desc "Portable CLI for composing Terraform stacks from provider catalogs."
  homepage "https://github.com/tiziano093/infra-composer-cli"
  version "2.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.2.0/infra-composer_2.2.0_darwin_amd64.tar.gz"
      sha256 "f0ba38128aa6cded60d06b476cb5d295893fb7a620699fb9432ac7d9a6e128bf"

      define_method(:install) do
        bin.install "infra-composer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.2.0/infra-composer_2.2.0_darwin_arm64.tar.gz"
      sha256 "0a81f46fe5658ea9ca3ff60a7044814ac903b8086072374716b09107b714391f"

      define_method(:install) do
        bin.install "infra-composer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.2.0/infra-composer_2.2.0_linux_amd64.tar.gz"
      sha256 "84577983a654defd228ca775c79d4e784485743f6edb7d69c6985f829df7f820"
      define_method(:install) do
        bin.install "infra-composer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.2.0/infra-composer_2.2.0_linux_arm64.tar.gz"
      sha256 "56fe13ff64f2b4ac1a3e4bb3c6a8f7e2809887697cdef51f235f6a6f96d7800f"
      define_method(:install) do
        bin.install "infra-composer"
      end
    end
  end

  test do
    system "#{bin}/infra-composer", "--version"
  end
end
