# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfraComposer < Formula
  desc "Portable CLI for composing Terraform stacks from provider catalogs."
  homepage "https://github.com/tiziano093/infra-composer-cli"
  version "2.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.3.0/infra-composer_2.3.0_darwin_amd64.tar.gz"
      sha256 "483f8a9dea56316fe19ccf0afbb9ef9511f7c8299ff76f791969ae0ae2d9e6fb"

      define_method(:install) do
        bin.install "infra-composer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.3.0/infra-composer_2.3.0_darwin_arm64.tar.gz"
      sha256 "55484b7a66c907f8a35d58e1376cc5654313de93fcf3b21c30c7668bdc307955"

      define_method(:install) do
        bin.install "infra-composer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.3.0/infra-composer_2.3.0_linux_amd64.tar.gz"
      sha256 "c346ce96ab4ba560940f6b71fda6961e0b5368af0204aed5ac1e06658da04f8f"
      define_method(:install) do
        bin.install "infra-composer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiziano093/infra-composer-cli/releases/download/v2.3.0/infra-composer_2.3.0_linux_arm64.tar.gz"
      sha256 "31d2c74b89536dae79ca1a31a3b4b305f13e0f167c699ed8c30bc82533fb9926"
      define_method(:install) do
        bin.install "infra-composer"
      end
    end
  end

  test do
    system "#{bin}/infra-composer", "--version"
  end
end
